name: GenomicExplorer
channels:
  - conda-forge
  - bioconda
channel_priority: strict

dependencies:
  # -------------------------
  # Python / GUI
  # -------------------------
  - python=3.11
  - pip=26.0.1
  - openpyxl=3.1.5
  - pyside6=6.9.0 # unstable installation using micromamba
  - numpy=2.4.2
  - pandas=3.0.1
  - scipy=1.17.1
  - matplotlib-base=3.10.8
  - pyyaml=6.0.3
  - plotly=6.5.2
  - python-kaleido=1.2.0
  - openjdk=23.0.2
 
  # -------------------------
  # External tools which could not be installed using micromamba in Windows
  # -------------------------
  #- plink2=2.0.0a.6.9
  #- bcftools=1.23
  #- blast=2.17.0
  #- braker3=3.0.6
  #- augustus=3.5.0
  #- snap=2017_03_01
  #- eggnog-mapper=2.1.13

  # -------------------------
  # R (core)
  # -------------------------
  - r-base=4.4.2
  - r-devtools=2.4.6
  - r-jsonlite=2.0.0
  - r-optparse=1.7.5
  - r-data.table=1.17.8
  - r-ggplot2=4.0.2
  - r-plotly=4.12.0
  - r-htmlwidgets=1.6.4
  - r-remotes=2.5.0

  # QTL/GWAS/GP
  - r-qtl=1.74
  - r-qtl2=0.38
  - r-gaston=1.6
  - r-bglr=1.1.4
  - r-glmnet=4.1_10
  - r-ranger=0.18.0
  - r-randomforestsrc=3.5.1

  # 次元削減/補完
  - r-uwot=0.2.4
  - r-rtsne=0.17
  - r-mclust=6.1.2
  - r-mice=3.19.0
  - r-missforest=1.6.1